### PR TITLE
Major refactoring of structure and style

### PR DESCRIPTION
**Pull request by tliron**
Issues addressed:

* Separate packages per controller
* Avoid duplication via common functions
* Consistent and clear variable and function names
* Go styling and conventions
* Removed unused code and comments
* English spelling mistakes
* A few missing/incomplete copyright headers
* Improvements to logging
* Remove `replace` statements in go.mod and update all dependencies

### CODE REVIEW

**Comment by tliron** [comment]
Issues addressed:

* Files too big: added more, reorganized, and split out a separate package
* Code duplication (still more work to be done, especially with tests)
* Consistent variable and function names with clearer names
* Go styling oddities
* Removed unused code
* English spelling mistakes

**Comment by denysaleksandrov** [comment]
Are you sure your branch is from the latest main commit? I see some `fmt.Println` code in smfcontroller, which I removed in [here](https://github.com/nephio-project/free5gc/pull/25).
Also interface names in tests are still uppercase, which was changed in the same PR.

**Comment by johnbelamaric** [comment]
> Are you sure your branch is from the latest main commit? I see some `fmt.Println` code in smfcontroller, which I removed in [here](https://github.com/nephio-project/free5gc/pull/25).
> 
> Also interface names in tests are still uppercase, which was changed in the same PR.

Updates to kubebuilder directives and CRDs are also missing.

**Comment by tliron** [comment]
I was quite sure it was the latest commit, but I might have been wrong. I can copy paste those fixes.

**Comment by johnbelamaric** [comment]
> I was quite sure it was the latest commit, but I might have been wrong. I can copy paste those fixes.

You can probably figure out which new commits were missed and just replicate the changes. I don't think there were many.

**Comment by tliron** [comment]
OK, @johnbelamaric and @denysaleksandrov, I think both of those issues were fixes. I'm confused by how this happened, I was sure to pull and hard reset my branch before beginning work. Maybe I was pointing to a wrong branch. Oh well, it will be easy to catch missing fixes. Sorry about this!

**Comment by denysaleksandrov** [comment]
@tliron seems to be working. I have not tried to setup a call though:
```
ubuntu@nephio-r1-e2e-denys:~/nephio/nephio-free5gc$ make run
test -s /home/ubuntu/nephio/nephio-free5gc/bin/controller-gen || GOBIN=/home/ubuntu/nephio/nephio-free5gc/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.11.4
/home/ubuntu/nephio/nephio-free5gc/bin/controller-gen rbac:roleName=free5gc-operator-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/ubuntu/nephio/nephio-free5gc/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
go run ./main.go
2023-06-12T07:18:02Z	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": ":8080"}
2023-06-12T07:18:02Z	INFO	setup	starting manager
2023-06-12T07:18:02Z	INFO	Starting server	{"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
2023-06-12T07:18:02Z	INFO	Starting server	{"kind": "health probe", "addr": "[::]:8081"}
2023-06-12T07:18:02Z	INFO	Starting EventSource	{"controller": "upfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "UPFDeployment", "source": "kind source: *v1alpha1.UPFDeployment"}
2023-06-12T07:18:02Z	INFO	Starting EventSource	{"controller": "smfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "SMFDeployment", "source": "kind source: *v1alpha1.SMFDeployment"}
2023-06-12T07:18:02Z	INFO	Starting EventSource	{"controller": "amfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "AMFDeployment", "source": "kind source: *v1alpha1.AMFDeployment"}
2023-06-12T07:18:02Z	INFO	Starting EventSource	{"controller": "upfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "UPFDeployment", "source": "kind source: *v1.Deployment"}
2023-06-12T07:18:02Z	INFO	Starting EventSource	{"controller": "upfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "UPFDeployment", "source": "kind source: *v1.ConfigMap"}
2023-06-12T07:18:02Z	INFO	Starting Controller	{"controller": "upfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "UPFDeployment"}
2023-06-12T07:18:02Z	INFO	Starting EventSource	{"controller": "smfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "SMFDeployment", "source": "kind source: *v1.Deployment"}
2023-06-12T07:18:02Z	INFO	Starting EventSource	{"controller": "smfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "SMFDeployment", "source": "kind source: *v1.ConfigMap"}
2023-06-12T07:18:02Z	INFO	Starting Controller	{"controller": "smfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "SMFDeployment"}
2023-06-12T07:18:02Z	INFO	Starting EventSource	{"controller": "amfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "AMFDeployment", "source": "kind source: *v1.Deployment"}
2023-06-12T07:18:02Z	INFO	Starting EventSource	{"controller": "amfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "AMFDeployment", "source": "kind source: *v1.ConfigMap"}
2023-06-12T07:18:02Z	INFO	Starting Controller	{"controller": "amfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "AMFDeployment"}
2023-06-12T07:18:02Z	INFO	Starting workers	{"controller": "upfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "UPFDeployment", "worker count": 1}
2023-06-12T07:18:02Z	INFO	Starting workers	{"controller": "amfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "AMFDeployment", "worker count": 1}
2023-06-12T07:18:02Z	INFO	Starting workers	{"controller": "smfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "SMFDeployment", "worker count": 1}
2023-06-12T07:29:12Z	INFO	Creating UPFDeployment configmap	{"controller": "upfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "UPFDeployment", "UPFDeployment": {"name":"free5gc-upf-1","namespace":"upf-1"}, "namespace": "upf-1", "name": "free5gc-upf-1", "reconcileID": "039b6056-c7b2-4d85-9acb-e22cd7616383", "UPFDeployment": "upf-1/free5gc-upf-1", "UPFDeployment.namespace": "upf-1", "ConfigMap.name": "free5gc-upf-1-upf-configmap"}
2023-06-12T07:29:12Z	INFO	Creating UPFDeployment	{"controller": "upfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "UPFDeployment", "UPFDeployment": {"name":"free5gc-upf-1","namespace":"upf-1"}, "namespace": "upf-1", "name": "free5gc-upf-1", "reconcileID": "039b6056-c7b2-4d85-9acb-e22cd7616383", "UPFDeployment": "upf-1/free5gc-upf-1", "UPFDeployment.namespace": "upf-1", "UPFDeployment.name": "free5gc-upf-1"}
2023-06-12T07:29:12Z	INFO	KubeAPIWarningLogger	would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "upf" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "upf" must set securityContext.capabilities.drop=["ALL"]; container "upf" must not include "NET_ADMIN" in securityContext.capabilities.add), runAsNonRoot != true (pod or container "upf" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "upf" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
2023-06-12T07:31:00Z	INFO	UPFDeployment resource not found. Ignoring since object must be deleted	{"controller": "upfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "UPFDeployment", "UPFDeployment": {"name":"free5gc-upf-1","namespace":"upf-1"}, "namespace": "upf-1", "name": "free5gc-upf-1", "reconcileID": "03e2843a-510d-47d6-828c-4b3a913d0050", "UPFDeployment": "upf-1/free5gc-upf-1"}
2023-06-12T07:31:00Z	INFO	UPFDeployment resource not found. Ignoring since object must be deleted	{"controller": "upfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "UPFDeployment", "UPFDeployment": {"name":"free5gc-upf-1","namespace":"upf-1"}, "namespace": "upf-1", "name": "free5gc-upf-1", "reconcileID": "c0142bf5-72cf-46e9-ae9c-d524c6148c01", "UPFDeployment": "upf-1/free5gc-upf-1"}
2023-06-12T07:31:00Z	INFO	UPFDeployment resource not found. Ignoring since object must be deleted	{"controller": "upfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "UPFDeployment", "UPFDeployment": {"name":"free5gc-upf-1","namespace":"upf-1"}, "namespace": "upf-1", "name": "free5gc-upf-1", "reconcileID": "14bb271f-a2dd-4899-863d-d9466e14dd54", "UPFDeployment": "upf-1/free5gc-upf-1"}
2023-06-12T07:31:09Z	INFO	Creating UPFDeployment configmap	{"controller": "upfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "UPFDeployment", "UPFDeployment": {"name":"free5gc-upf-1","namespace":"upf-1"}, "namespace": "upf-1", "name": "free5gc-upf-1", "reconcileID": "426a424c-74fa-48b1-9fe9-d329ab2cf4bf", "UPFDeployment": "upf-1/free5gc-upf-1", "UPFDeployment.namespace": "upf-1", "ConfigMap.name": "free5gc-upf-1-upf-configmap"}
2023-06-12T07:31:09Z	INFO	Creating UPFDeployment	{"controller": "upfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "UPFDeployment", "UPFDeployment": {"name":"free5gc-upf-1","namespace":"upf-1"}, "namespace": "upf-1", "name": "free5gc-upf-1", "reconcileID": "426a424c-74fa-48b1-9fe9-d329ab2cf4bf", "UPFDeployment": "upf-1/free5gc-upf-1", "UPFDeployment.namespace": "upf-1", "UPFDeployment.name": "free5gc-upf-1"}
2023-06-12T07:32:17Z	INFO	Creating SMFDeployment configmap	{"controller": "smfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "SMFDeployment", "SMFDeployment": {"name":"free5gc-smf-1","namespace":"nrf"}, "namespace": "nrf", "name": "free5gc-smf-1", "reconcileID": "e3318c13-7c99-467c-8f5c-50576dd9de3c", "SMFDeployment": "nrf/free5gc-smf-1", "SMFDeployment.namespace": "nrf", "ConfigMap.name": "free5gc-smf-1-smf-configmap"}
2023-06-12T07:32:17Z	INFO	Creating SMFDeployment service	{"controller": "smfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "SMFDeployment", "SMFDeployment": {"name":"free5gc-smf-1","namespace":"nrf"}, "namespace": "nrf", "name": "free5gc-smf-1", "reconcileID": "e3318c13-7c99-467c-8f5c-50576dd9de3c", "SMFDeployment": "nrf/free5gc-smf-1", "SMFDeployment.namespace": "nrf", "Service.name": "smf-nsmf"}
2023-06-12T07:32:17Z	INFO	Creating SMFDeployment	{"controller": "smfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "SMFDeployment", "SMFDeployment": {"name":"free5gc-smf-1","namespace":"nrf"}, "namespace": "nrf", "name": "free5gc-smf-1", "reconcileID": "e3318c13-7c99-467c-8f5c-50576dd9de3c", "SMFDeployment": "nrf/free5gc-smf-1", "SMFDeployment.namespace": "nrf", "SMFDeployment.name": "free5gc-smf-1"}
2023-06-12T07:32:31Z	INFO	Creating AMFDeployment configmap	{"controller": "amfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "AMFDeployment", "AMFDeployment": {"name":"free5gc-amf-1","namespace":"nrf"}, "namespace": "nrf", "name": "free5gc-amf-1", "reconcileID": "41dcd5be-eca8-4a71-b87c-a5f5660b4789", "AMFDeployment": "nrf/free5gc-amf-1", "AMFDeployment.namespace": "nrf", "ConfigMap.name": "free5gc-amf-1-amf-configmap"}
2023-06-12T07:32:31Z	INFO	Creating AMFDeployment service	{"controller": "amfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "AMFDeployment", "AMFDeployment": {"name":"free5gc-amf-1","namespace":"nrf"}, "namespace": "nrf", "name": "free5gc-amf-1", "reconcileID": "41dcd5be-eca8-4a71-b87c-a5f5660b4789", "AMFDeployment": "nrf/free5gc-amf-1", "AMFDeployment.namespace": "nrf", "Service.name": "free5gc-amf-1-amf-svc"}
2023-06-12T07:32:31Z	INFO	Creating AMFDeployment	{"controller": "amfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "AMFDeployment", "AMFDeployment": {"name":"free5gc-amf-1","namespace":"nrf"}, "namespace": "nrf", "name": "free5gc-amf-1", "reconcileID": "41dcd5be-eca8-4a71-b87c-a5f5660b4789", "AMFDeployment": "nrf/free5gc-amf-1", "AMFDeployment.namespace": "nrf", "AMFDeployment.name": "free5gc-amf-1"}
```

All test pass as well.

**Comment by denysaleksandrov** [comment]
AMF is crashing:
```
nrf                            free5gc-amf-1-5ccc94f547-hb4r8                       0/1     CrashLoopBackOff   6 (3m43s ago)   9m23s
nrf                            free5gc-ausf-7d494d668d-72dxq                        1/1     Running            0               23m
nrf                            free5gc-nrf-66cc98cfc5-48qpb                         1/1     Running            0               23m
nrf                            free5gc-nssf-668db85d54-dcr62                        1/1     Running            0               23m
nrf                            free5gc-pcf-55d4bfd648-n6gfc                         1/1     Running            0               23m
nrf                            free5gc-smf-1-597dbfdbcb-cjp86                       1/1     Running            0               9m37s
nrf                            free5gc-udm-845db6c9c8-dn84t                         1/1     Running            0               23m
nrf                            free5gc-udr-79466f7f86-58v42                         1/1     Running            0               23m
nrf                            free5gc-webui-84ff8c456c-dfbh8                       1/1     Running            0               23m
nrf                            mongodb-0                                            1/1     Running            0               23m
resource-group-system          resource-group-controller-manager-6cdfc6486d-rqmh4   3/3     Running            0               5d
upf-1                          free5gc-upf-1-588f54b5c6-tpp4g                       1/1     Running            0               10m
ubuntu@nephio-r1-e2e-denys:~/nephio/nephio-free5gc$ k logs free5gc-amf-1-5ccc94f547-hb4r8 -n nrf
2023-06-12T07:38:11Z [ERRO][AMF][CFG] yaml: line 10: did not find expected '-' indicator
2023-06-12T07:38:11Z [ERRO][AMF][CFG] [-- PLEASE REFER TO SAMPLE CONFIG FILE COMMENTS --]
2023-06-12T07:38:11Z [ERRO][AMF][App] AMF Run error: Failed to initialize !!
```

**Comment by tliron** [comment]
In the latest push I also remove all the `replace` statements in our `go.mod`. It seems to be compiling and working OK with the latest Controller Runtime and K8s client API.

**Pull request merged**
