### PR TITLE
Add UPFDeployment controller

### PR DESCRIPTION
**Pull request by denysaleksandrov**
Adding UPFDeployment controller with:
- unit tests for non-Reconciler functions. More tests will be added once we defined the setup for Integration and Func testing.
- SecurityContext added to Deployment.Spec.Template.Spec.Containers
- UPFDeployment status fields OperationStatus and OperationUpTime updated after upfdeployment is created
- multiple DNNs are possible to be provided in the spec
- logging added
- checking if all required NADs exist in a namespace before creating a deployment object
- reconcile periodically to update UPFDeployment status in the case underlying pods status changes.

I am using the following API file before the updated file is checked in the API repo:
upfdeployv1alpha1 "github.com/nephio-project/nephio-pocs/nephio-5gc-controller/apis/nf/v1alpha1"

Tested with two UPFDeployments in different namespaces:
```
upf-1                 free5gc-upf-1-7cb78c8b78-x22d8                1/1     Running   0          14h
upf-2                 free5gc-upf-2-55fc6c977b-6qd7h                1/1     Running   0          33m
```

Logs:
```
 k logs pod/free5gc-upf-1-7cb78c8b78-x22d8 -n upf-1
RTNETLINK answers: File exists
2023-04-05T22:18:39Z [INFO][UPF][Util] UPF log: /free5gc/free5gc-upfd/log/upf.log
2023-04-05T22:18:39Z [INFO][UPF][Util] Config: /free5gc/config/..2023_04_05_22_18_38.1725034701/upfcfg.yaml
2023-04-05T22:18:39Z [INFO][UPF][Util] UPF config version [1.0.0]
2023-04-05T22:18:39Z [INFO][UPF][Util] Set log level: info
2023-04-05T22:18:39Z [INFO][UPF][Util] DNN routes added, main routing table:
2023-04-05T22:18:39Z [INFO][UPF][Util] DstIp               Gateway        Iface     Priority RtProto   Type
2023-04-05T22:18:39Z [INFO][UPF][Util] 192.168.203.0 /24   0.0.0.0        n6-2      0        kernel    unicast
2023-04-05T22:18:39Z [INFO][UPF][Util] 192.168.103.0 /24   0.0.0.0        n6-1      0        kernel    unicast
2023-04-05T22:18:39Z [INFO][UPF][Util] 192.168.100.0 /24   0.0.0.0        n4-1      0        kernel    unicast
2023-04-05T22:18:39Z [INFO][UPF][Util] 10.98.0.1 /32       0.0.0.0        eth0      0        boot      unicast
2023-04-05T22:18:39Z [INFO][UPF][Util] 10.98.0.0 /24       10.98.0.1      eth0      0        boot      unicast
2023-04-05T22:18:39Z [INFO][UPF][Util] 10.30.0.0 /16       0.0.0.0        upfgtp    0        static    unicast    <<< DNN internet
2023-04-05T22:18:39Z [INFO][UPF][Util] 10.20.0.0 /16       0.0.0.0        upfgtp    0        static    unicast    <<< DNN private
2023-04-05T22:18:39Z [INFO][UPF][Util] 10.10.5.0 /24       0.0.0.0        n3-1      0        kernel    unicast
2023-04-05T22:18:39Z [INFO][UPF][Util] 0.0.0.0 /0          10.98.0.1      eth0      0        boot      unicast
```

ConfigMap
```
❯ k get cm/free5gc-upf-1-upf-configmap -n upf-1 -o yaml
apiVersion: v1
data:
  upfcfg.yaml: |2

    info:
      version: 1.0.0
      description: UPF configuration

    configuration:
      ReportCaller: false
      debugLevel: info
      dnn_list:
      - cidr: 10.20.0.0/16
        dnn: internet
        natifname: n6
      - cidr: 10.30.0.0/16
        dnn: private
        natifname: n6
      pfcp:
        - addr: 192.168.100.3

      gtpu:
        - addr: 10.10.5.3
        # [optional] gtpu.name
        # - name: upf.5gc.nctu.me
        # [optional] gtpu.ifname
        # - ifname: gtpif
  wrapper.sh: |
    #!/bin/sh

    ### Implement networking rules
    iptables -A FORWARD -j ACCEPT
    iptables -t nat -A POSTROUTING -s 10.20.0.0/16 -o n6-1 -j MASQUERADE  # route traffic comming from the UE  SUBNET to the interface N6
    iptables -t nat -A POSTROUTING -s 10.30.0.0/16 -o n6-2 -j MASQUERADE  # route traffic comming from the UE  SUBNET to the interface N6
    echo "1200 n6if" >> /etc/iproute2/rt_tables # create a routing table for the interface N6
    ip rule add from 10.20.0.0/16 table n6if   # use the created ip table to route the traffic comming from  the UE SUBNET
    ip route add default via 192.168.103.1 dev n6-1 table n6if  # add a default route in the created table so  that all UEs will use this gateway for external communications (target IP not in the Data Network attached  to the interface N6) and then the Data Network will manage to route the traffic
    ip rule add from 10.30.0.0/16 table n6if   # use the created ip table to route the traffic comming from  the UE SUBNET
    ip route add default via 192.168.203.1 dev n6-2 table n6if  # add a default route in the created table so  that all UEs will use this gateway for external communications (target IP not in the Data Network attached  to the interface N6) and then the Data Network will manage to route the traffic

    /free5gc/free5gc-upfd/free5gc-upfd -c /free5gc/config//upfcfg.yaml
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-05T22:08:35Z"
  name: free5gc-upf-1-upf-configmap
  namespace: upf-1
  resourceVersion: "332199"
  uid: 26d195db-45e4-40ee-b565-c4f10d2fed23
```

### CODE REVIEW

**Comment by denysaleksandrov** [comment]
Makes sense to squash to keep the history clean. Should I squash locally or it will be done on merge?

**Comment by tliron** [comment]
I don't think GitHub can automatically squash...

**Pull request closed without merging**
